# Scons build script, 
import sys
import glob
# create a static library
StaticLibrary(
		'logger',
		glob.glob('./src/*.c'),
		CPPPATH=['./inc'], 
		CFLAGS = ['-Wall','-ggdb',]
		)

if 'logger_disable_test' in COMMAND_LINE_TARGETS:
	# logger is disabled.
	Program(
		'logger_disable_test',
		glob.glob('./testapp/*.cpp'),
		CPPPATH=['./inc'], 
		CPPFLAGS = ['-Wall','-ggdb', '-DDISABLE_ALL_LOGS',],
		)
else :
	# program using the logger. 
	Program(
		'logger_test',
		glob.glob('./testapp/*.cpp'),
		CPPPATH=['./inc'], 
		CPPFLAGS = ['-Wall','-ggdb',],
		LIBS	= ['logger'],
		LIBPATH	= ['.']
	)

# create a shared library.
SharedLibrary(
		'logger',
		glob.glob('./src/*.c'),
		CPPPATH=['./inc'], 
		CFLAGS = ['-Wall','-ggdb',]
		)

